### ISSUE TITLE
Submission of changes to the Plugin Hub

### ISSUE THREAD

**Issue by stinodes** [MitchBarnett/wiki-bank-tag-integration#15]
There seems to have been quite some code-changes, but no update to the plugin hub.
Is there any reason for this? Someone created a PR for an updated fork, which got denied (since it's just a copy of this repo).

**Comment by steveacalabro** [comment]
Check out https://github.com/MitchBarnett/wiki-bank-tag-integration/issues/10, I took lead and submitted this version to the plugin hub after manual validation. So here's hoping. More updates will be in that issue

> Tested [491d705](https://github.com/MitchBarnett/wiki-bank-tag-integration/commit/491d7054b3dfb34f66e7c30ed66712a973086128) locally and it works.
> 
> Forked the plugin-hub repo and it appears the commit being used is this
> 
> [233f143](https://github.com/MitchBarnett/wiki-bank-tag-integration/commit/233f143f9994558bb44696411eccc6fd74d92d88)
> 
> I updated that to match the latest commit on this repo [491d705](https://github.com/MitchBarnett/wiki-bank-tag-integration/commit/491d7054b3dfb34f66e7c30ed66712a973086128)
> 
> That PR has been submitted to the [plugin hub repo here](https://github.com/runelite/plugin-hub/pull/6171)
